spring:
  datasource:
    name: backend
    url: jdbc:postgresql://localhost:5432/backend?autoreconnect=true
    username: postgres
    password: Emilio11022003
  web:
    cors:
      allowed-origin-patterns: "http://localhost:5173"
      allow-credentials: true
      allow-headers: "*"


mybatis:
  config-location: classpath:mybatis-config.xml
  type-handlers-package: com.info404.backend.handlers
